spring.datasource.url=jdbc:postgresql://localhost:5432/meuinfluencer
spring.datasource.password=admin123
spring.datasource.username=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
spring.docker.compose.lifecycle-management=start_and_stop
spring.docker.compose.enabled=false
spring.jpa.hibernate.ddl-auto=update
mercadopago.access.token= TEST-4890978009801799-040519-fea25619ef19d02c36dcbd67a6b9ab4a-1233175894